apiVersion: apps/v1
kind: Deployment
metadata:
  name: laptops-app
  labels:
    type: api
    service: laptops-app
    language: python
spec:
  replicas: 3
  selector:
    matchLabels:
      type: api
      service: laptops-app
  template:
    metadata:
      labels:
        type: api
        service: laptops-app
        language: python
    spec:
      containers:
        - name: api
          image: kinginspecial/laptops-app:v1
          env:
            - name: AWS_ACCESS_KEY_ID
              value: <aws-access-key>
            - name: AWS_SECRET_ACCESS_KEY
              value: <aws-secret-access-key>
